// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8If33FxJZXqkfqkdUvvbn8qWUKkARXQ4',
    appId: '1:994117220370:web:2c646cec146736070940cb',
    messagingSenderId: '994117220370',
    projectId: 'coinwelldigital',
    authDomain: 'coinwelldigital.firebaseapp.com',
    storageBucket: 'coinwelldigital.firebasestorage.app',
    measurementId: 'G-2ZPQXGES8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaH0o_dLlW461THY0cOTMPC1av555_QSo',
    appId: '1:994117220370:android:8d565532c11bd6290940cb',
    messagingSenderId: '994117220370',
    projectId: 'coinwelldigital',
    storageBucket: 'coinwelldigital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HAraCOOO4JiiVBbTphRQ-_9As99PpIk',
    appId: '1:994117220370:ios:1935d6fef71cb68c0940cb',
    messagingSenderId: '994117220370',
    projectId: 'coinwelldigital',
    storageBucket: 'coinwelldigital.firebasestorage.app',
    iosBundleId: 'com.example.coinwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HAraCOOO4JiiVBbTphRQ-_9As99PpIk',
    appId: '1:994117220370:ios:1935d6fef71cb68c0940cb',
    messagingSenderId: '994117220370',
    projectId: 'coinwelldigital',
    storageBucket: 'coinwelldigital.firebasestorage.app',
    iosBundleId: 'com.example.coinwell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8If33FxJZXqkfqkdUvvbn8qWUKkARXQ4',
    appId: '1:994117220370:web:a35f072e398f65d60940cb',
    messagingSenderId: '994117220370',
    projectId: 'coinwelldigital',
    authDomain: 'coinwelldigital.firebaseapp.com',
    storageBucket: 'coinwelldigital.firebasestorage.app',
    measurementId: 'G-EQPMBHDQ9B',
  );
}
